name: Lint & Type Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install black==23.11.0 flake8==6.1.0 mypy==1.7.1

      - name: Black (format check)
        run: |
          black --check .

      - name: Flake8 (lint)
        run: |
          flake8 src tests

      - name: Mypy (type check)
        run: |
          mypy src tests